(() => {
  'use strict';
  const content = window.ANANKE_CONTENT || {};
  const artists = (content.artists || []).filter(artist => typeof artist.name === 'string' && artist.name.trim());
  const $ = selector => document.querySelector(selector);
  const make = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
  const safeURL = value => { if (!value) return ''; try { const url = new URL(value, location.href); return ['https:', 'http:', 'file:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } };
  const phone = value => { let number = String(value || '').replace(/\D/g, ''); if (number.length === 10 || number.length === 11) number = '55' + number; return /^55\d{10,11}$/.test(number) ? number : ''; };
  const studioPhone = phone(content.whatsapp) || '5531997231459';
  const contact = artist => { const direct = artist.isPlaceholder ? '' : phone(artist.whatsapp); const message = artist.isPlaceholder ? 'Olá, ANANKE! Vi a página da equipe e gostaria de conhecer os artistas e conversar sobre uma tattoo.' : direct ? `Olá, ${artist.name}! Conheci seu trabalho pelo site da ANANKE e gostaria de conversar sobre uma tattoo.` : `Olá, ANANKE! Gostaria de falar com ${artist.name} sobre uma tattoo. Podem me ajudar?`; return { url: `https://wa.me/${direct || studioPhone}?text=${encodeURIComponent(message)}`, direct: Boolean(direct) }; };
  const contactNote = artist => artist.isPlaceholder ? 'Contato com o estúdio ANANKE.' : contact(artist).direct ? `WhatsApp de ${artist.name}.` : `Atendimento pelo estúdio para falar com ${artist.name}.`;
  const fallbackPortrait = artist => { const wrapper = make('div', 'member-portrait-placeholder'); const initials = artist.name.trim().split(/\s+/).slice(0, 2).map(word => word[0]).join('').toUpperCase(); wrapper.append(make('span', 'member-initials', initials), make('span', 'member-photo-note', 'FOTO EM BREVE')); return wrapper; };
  function portrait(artist, lazy = true) { const url = safeURL(artist.photo); if (!url) return fallbackPortrait(artist); const img = make('img'); img.src = url; img.alt = artist.isPlaceholder ? `Foto ilustrativa para ${artist.name}; não representa um integrante confirmado da ANANKE` : `Retrato de ${artist.name}, equipe ANANKE`; img.loading = lazy ? 'lazy' : 'eager'; img.width = 600; img.height = 750; img.addEventListener('error', () => img.replaceWith(fallbackPortrait(artist)), { once: true }); return img; }
  function whatsappLink(artist) { const link = make('a', 'button member-whatsapp'); link.href = contact(artist).url; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.setAttribute('aria-label', artist.isPlaceholder ? 'Conversar com o estúdio ANANKE no WhatsApp' : contact(artist).direct ? `Conversar com ${artist.name} no WhatsApp` : `Pedir atendimento com ${artist.name} pelo WhatsApp do estúdio`); const icon = make('img'); icon.src = 'assets/whatsapp.svg'; icon.alt = ''; icon.width = 22; icon.height = 22; const arrow = make('span', '', '↗'); arrow.setAttribute('aria-hidden', 'true'); link.append(icon, document.createTextNode('Conversar pelo WhatsApp'), arrow); return link; }
  const dialog = $('#member-dialog');
  let returnFocus = null;
  function openProfile(artist, trigger) { returnFocus = trigger; $('#profile-name').textContent = artist.name; $('#profile-reference').hidden = !artist.isPlaceholder; $('#profile-specialty').textContent = artist.specialty || 'Equipe ANANKE'; $('#profile-bio').textContent = artist.bio || 'Converse sobre sua ideia, conheça os trabalhos e descubra as possibilidades para sua próxima tattoo.'; $('#profile-portrait').replaceChildren(portrait(artist, false)); $('#profile-whatsapp').href = contact(artist).url; $('#profile-whatsapp').setAttribute('aria-label', artist.isPlaceholder ? 'Conversar com o estúdio ANANKE' : `Conversar sobre uma tattoo com ${artist.name}`); $('#profile-destination').textContent = contactNote(artist); const instagram = safeURL(artist.instagram); $('#profile-instagram').hidden = !instagram; if (instagram) $('#profile-instagram').href = instagram; else $('#profile-instagram').removeAttribute('href'); dialog.showModal(); document.body.classList.add('modal-open'); }
  artists.forEach(artist => { const card = make('article', 'member-card'); const imageButton = make('button', 'member-portrait'); imageButton.type = 'button'; imageButton.setAttribute('aria-label', `Conhecer ${artist.name}`); imageButton.append(portrait(artist), make('span', 'member-profile-hint', 'Ver perfil ↗')); if (artist.isPlaceholder) imageButton.append(make('span', 'member-reference-badge', 'FOTO ILUSTRATIVA')); imageButton.addEventListener('click', () => openProfile(artist, imageButton)); const body = make('div', 'member-card-body'); body.append(make('h3', '', artist.name), make('p', 'member-specialty', artist.specialty || 'Equipe ANANKE')); if (artist.bio && !artist.isPlaceholder) body.append(make('p', 'member-bio', artist.bio)); const actions = make('div', 'member-actions'); actions.append(whatsappLink(artist), make('p', 'contact-destination', contactNote(artist))); const more = make('button', 'member-profile-button', 'Ver apresentação ↗'); more.type = 'button'; more.addEventListener('click', () => openProfile(artist, more)); actions.append(more); body.append(actions); card.append(imageButton, body); $('#member-grid').append(card); });
  $('#member-empty').hidden = artists.length > 0; $('#member-reference-note').hidden = !artists.some(artist => artist.isPlaceholder);
  $('.profile-close').addEventListener('click', () => dialog.close());
  dialog.addEventListener('close', () => { document.body.classList.remove('modal-open'); returnFocus?.focus(); });
  dialog.addEventListener('click', event => { if (event.target !== dialog) return; const rect = dialog.getBoundingClientRect(); if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) dialog.close(); });
  document.querySelectorAll('[data-team-contact]').forEach(link => { link.href = `https://wa.me/${studioPhone}?text=${encodeURIComponent('Olá, ANANKE! Quero conhecer os artistas e encontrar quem combina com a minha ideia de tattoo.')}`; });
  $('#year').textContent = new Date().getFullYear();
})();
